inherit_gem:
  srp-style:
    - rubocop.yml
    - rubocop_performance.yml
    - rubocop_rake.yml
    - rubocop_thread_safety.yml

AllCops:
  UseCache: true
  MaxFilesInCache: 20000
  Exclude:
    - bin/**/*

Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*

